# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
    ]
